name: Deploy to Firebase Hosting on merge
on:
  push:
    branches: [main, dev]
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      IS_PRODUCTION: ${{ endsWith(github.ref, 'main') }}
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 9.12.3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with: 
          node-version: '22'
          cache: 'pnpm'
      
      - name: Set up firebase
        run: pnpm add -g firebase-tools

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build with dev env variables
        if: ${{ env.IS_PRODUCTION != 'true' }}
        run: pnpm build
        env:
          VITE_FIREBASE_API_KEY: ${{ secrets.DEV_FIREBASE_API_KEY }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.DEV_FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_DATABASE_URL: ${{ secrets.DEV_FIREBASE_DATABASE_URL }}
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.DEV_FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.DEV_FIREBASE_STORAGE_BUCKET }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.DEV_FIREBASE_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_APP_ID: ${{ secrets.DEV_FIREBASE_APP_ID }}
          VITE_FIREBASE_MEASUREMENT_ID: ${{ secrets.DEV_FIREBASE_MEASUREMENT_ID }}

      - name: Build with prod env variables
        if: ${{ env.IS_PRODUCTION == 'true' }}
        run: pnpm build
        env:
          VITE_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          VITE_FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ env.IS_PRODUCTION == 'true' && secrets.FIREBASE_SERVICE_ACCOUNT_NWPLUS_UBC || secrets.FIREBASE_SERVICE_ACCOUNT_NWPLUS_UBC_DEV }}
          projectId: ${{ env.IS_PRODUCTION == 'true' && 'nwplus-ubc' || 'nwplus-ubc-dev' }}
          channelId: live
          target: ${{ env.IS_PRODUCTION == 'true' && 'nwplus-ubc' || 'nwplus-ubc-dev' }}
